### ISSUE TITLE
Add checkbox to select all frames in visualizer

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [isl-org/Open3D-ML#315] opened 2021-07-11 22:25 UTC
I recently started using Open3D-ML and am really enjoying it - **thank you for the great work!**

Small feature request to go along with you dataset integration - a way to select all frames in the `List` of the visualizer, for the `animation`. Right now, when using the code below, you have to manually check every box to include it in the `Animation`

```python
import open3d.ml.tf as ml3d  # or open3d.ml.torch as ml3d

# construct a dataset by specifying dataset_path
DATASET: str = "kitti"  # or argoverse

if DATASET == "kitti":
    dataset = ml3d.datasets.KITTI(dataset_path="/path/to/datasets/Kitti")
elif DATASET == "argoverse":
    dataset = ml3d.datasets.Argoverse(dataset_path="/path/to/datasets/Argoverse/tracking")
else:
    raise ValueError(f"Received unknown dataset name: {DATASET}")

# get the 'all' split that combines training, validation and test set
data_split = dataset.get_split("train")

# show the first 100 frames using the visualizer
vis = ml3d.vis.Visualizer()

if __name__ == "__main__":

    vis.visualize_dataset(dataset, "train", indices=range(100), width=2500, height=1600)
```

gives:

![image](https://user-images.githubusercontent.com/12820901/125211562-74af6680-e2a7-11eb-87b4-478d04e2eaf3.png)

I cannot find a way to select all frames - perhaps there is one I don't know about?

**Comment by Nicholas-Mitchell** [comment] 2021-07-11 22:29
I found you can change a flag for that in `/path/to/python3.8/site-packages/open3d/_ml3d/vis/visualizer.py` at line 1582:

```python
    def _visualize(self, title, width, height):
        gui.Application.instance.initialize()
        self._init_user_interface(title, width, height)

        self._3d.scene.downsample_threshold = 400000

        # Turn all the objects off except the first one
        for name, node in self._name2treenode.items():
            node.checkbox.checked = True                 # Set this to True
            self._3d.scene.show_geometry(name, False)

```

**Comment by ssheorey** [comment] 2021-07-16 18:23
Duplicate of #291

**Comment by sanskar107** [comment] 2021-09-28 13:26
@Nicholas-Mitchell This feature has been merged to `dev` branch, you can try it. It will be merged to `master` in the next release (within a couple of weeks).

**Closed by sanskar107** 2021-09-28 13:26 UTC
Labels: visualization
